image: python:3.10

.default_rules: &default_rules
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_MERGE_REQUEST_ID'

stages:
  - build
  - test
  - code_quality

variables:
  VENV_DIR: venv
  PYTHONPATH: "${PYTHONPATH}:${CI_PROJECT_DIR}"

before_script:
  - python3 -m venv $VENV_DIR
  - source $VENV_DIR/bin/activate
  - pip install --upgrade pip
  - pip install .[dev,testing]

build:
  stage: build
  script:
    - echo "Install ok"
  <<: *default_rules

test:
  stage: test
  script:
    - pytest --cov=mirrowrs --cov-report=term-missing
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  <<: *default_rules

code_quality:
  stage: code_quality
  script:
    - echo "Code quality processing"
    - pylint mirrowrs/
    - isort --check-only mirrowrs/
    - black --check mirrowrs/
  <<: *default_rules


